# yaml 配置
name: yoyo_media_server
services:
  yoyo_emby:
    container_name: yoyo_emby
    image: amilys/embyserver:latest
    environment:
    #   - HTTP_PROXY=${PROXY}
    #   - HTTPS_PROXY=${PROXY}
    #   - NO_PROXY=127.0.0.1,localhost,192.168.*
    #   - PUID=0
    #   - PGID=0
        - TZ=Asia/Hong_Kong
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /var/lib/emby:/config
      - /mnt:/mnt
      - /media:/media
    ports:
      - 8096:8096
    restart: unless-stopped
    depends_on:
       - yoyo_rclone_alist
       - yoyo_alist


  yoyo_alist:
    container_name: yoyo_alist
    environment:
      - TZ=Asia/Hong_Kong
    image: xhofe/alist:latest
    volumes:
      - /opt/alist/data:/opt/alist/data
      - /mnt:/mnt
      - /media:/media
    ports:
      - 5244:5244
    depends_on:
      - yoyo_rclone_alist
    restart: unless-stopped
    
  yoyo_rclone_alist:
    container_name: yoyo_rclone_alist
    image: rclone/rclone:latest
    network_mode: host
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .config/rclone:/config/rclone
      - /mnt:/data:shared
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    command: mount alist_webdav:/ /data --allow-other --allow-non-empty --file-perms 0777 --multi-thread-streams 1024 --multi-thread-cutoff 128M --network-mode --vfs-cache-mode full --vfs-cache-max-size 10G --vfs-cache-max-age 12h --buffer-size 64K --vfs-read-chunk-size 1M --vfs-read-chunk-size-limit 50M --no-modtime --no-checksum --vfs-read-wait 0ms -v --ignore-size


  yoyo_nginx:
    container_name: yoyo_nginx
    environment:
      - TZ=Asia/Hong_Kong
    image: nginx:latest
    network_mode: host
    depends_on:
      - yoyo_emby
    volumes:
      # - /etc/nginx:/etc/nginx
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/emby2alist:/etc/nginx/emby2alist/
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/logs/debug:/etc/nginx/logs/debug
      - /var/cache/nginx/emby:/var/cache/nginx/emby
    restart: unless-stopped
    
